#!/bin/bash
#
# cluster/setup_3node.sh
#
# Starts a 3-node objstrd cluster on localhost using image files.
# Each node runs standalone (ROLE=node not yet implemented), but this
# script demonstrates the intended topology and serves as a template
# for when ROLE=coordinator/node is available.
#
# Layout:
#   node0: port 8100, image /tmp/cluster_node0.raw
#   node1: port 8101, image /tmp/cluster_node1.raw
#   node2: port 8102, image /tmp/cluster_node2.raw
#
# State is written to /tmp/cluster_state.sh so other scripts can source it.
#
# Usage:
#   bash setup_3node.sh          # start cluster
#   source /tmp/cluster_state.sh # get NODE0/NODE1/NODE2 variables
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../common/server.sh"

NODE_COUNT=3
BASE_PORT=8100
IMAGE_SIZE_MB=512
STATE_FILE=/tmp/cluster_state.sh

echo "=== Starting $NODE_COUNT-node cluster ==="

for i in $(seq 0 $((NODE_COUNT - 1))); do
    port=$((BASE_PORT + i))
    image="/tmp/cluster_node${i}.raw"
    rm -f "$image"
    start_server "$port" "$image" "$IMAGE_SIZE_MB"
done

# Write a state file so test scripts can source node addresses
{
    echo "# Generated by cluster/setup_3node.sh"
    for i in $(seq 0 $((NODE_COUNT - 1))); do
        port=$((BASE_PORT + i))
        hash=$(get_build_hash "$port")
        echo "NODE${i}_URL=http://localhost:${port}"
        echo "NODE${i}_HASH=${hash}"
        echo "NODE${i}_IMAGE=/tmp/cluster_node${i}.raw"
    done
    echo "NODE_URLS=\"$(for i in $(seq 0 $((NODE_COUNT - 1))); do echo -n "http://localhost:$((BASE_PORT + i)) "; done)\""
} > "$STATE_FILE"

echo ""
echo "Cluster ready. State written to $STATE_FILE"
echo "To stop: bash $SCRIPT_DIR/teardown.sh"
cat "$STATE_FILE"
